spring:
  application:
    # 服务名
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.192.1.12:8848

server:
  port: 8070

management:
  # 端点检查（Health Check）
  endpoints:
    web:
      exposure:
        include: "*"