version: "2"
services:
  nacos-standalone:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    environment:
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
    restart: always